version: "3"

services: 
    app:
        build:
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - //C:/temp1/recipe-app-api/app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"